// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package servies

import (
	"context"
	"fmt"

	"github.com/sah4ez/dapr-example/clients/servies/hasher"
	"github.com/sah4ez/dapr-example/clients/servies/jsonrpc"
	"github.com/sah4ez/dapr-example/interfaces/types"
)

type ClientUser struct {
	*ClientJsonRPC
}

type retUserGetNameByID = func(user types.User, err error)

func (cli *ClientUser) GetNameByID(ctx context.Context, id types.ID) (user types.User, err error) {

	request := requestUserGetNameByID{Id: id}
	var response responseUserGetNameByID
	var rpcResponse *jsonrpc.ResponseRPC
	cacheKey, _ := hasher.Hash(request)
	rpcResponse, err = cli.rpc.Call(ctx, "user.getnamebyid", request)
	var fallbackCheck func(error) bool
	if cli.fallbackUser != nil {
		fallbackCheck = cli.fallbackUser.GetNameByID
	}
	if rpcResponse != nil && rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
	}
	if err = cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response); err != nil {
		return
	}
	return response.User, err
}

func (cli *ClientUser) ReqGetNameByID(ctx context.Context, callback retUserGetNameByID, id types.ID) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "user.getnamebyid",
		Params:  requestUserGetNameByID{Id: id},
	}}
	if callback != nil {
		var response responseUserGetNameByID
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			cacheKey, _ := hasher.Hash(request.rpcRequest.Params)
			var fallbackCheck func(error) bool
			if cli.fallbackUser != nil {
				fallbackCheck = cli.fallbackUser.GetNameByID
			}
			if rpcResponse != nil && rpcResponse.Error != nil {
				if cli.errorDecoder != nil {
					err = cli.errorDecoder(rpcResponse.Error.Raw())
				} else {
					err = fmt.Errorf(rpcResponse.Error.Message)
				}
			}
			callback(response.User, cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response))
		}
	}
	return
}
