// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/dapr-example/interfaces"
)

type httpBalance struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverBalance
	base             interfaces.Balance
}

func NewBalance(svcBalance interfaces.Balance) (srv *httpBalance) {

	srv = &httpBalance{
		base: svcBalance,
		svc:  newServerBalance(svcBalance),
	}
	return
}

func (http *httpBalance) Service() MiddlewareSetBalance {
	return http.svc
}

func (http *httpBalance) WithLog() *httpBalance {
	http.svc.WithLog()
	return http
}

func (http *httpBalance) WithMetrics() *httpBalance {
	http.svc.WithMetrics()
	return http
}

func (http *httpBalance) WithErrorHandler(handler ErrorHandler) *httpBalance {
	http.errorHandler = handler
	return http
}

func (http *httpBalance) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/balance", http.serveBatch)
	route.Post("/api/v1/balance/getBalance", http.serveGetBalance)
}
