// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"
	"time"

	"github.com/go-kit/kit/metrics"
	"github.com/sah4ez/dapr-example/interfaces"
	"github.com/sah4ez/dapr-example/interfaces/types"
)

type metricsBalance struct {
	next            interfaces.Balance
	requestCount    metrics.Counter
	requestCountAll metrics.Counter
	requestLatency  metrics.Histogram
}

func metricsMiddlewareBalance(next interfaces.Balance) interfaces.Balance {
	return &metricsBalance{
		next:            next,
		requestCount:    RequestCount.With("service", "Balance"),
		requestCountAll: RequestCountAll.With("service", "Balance"),
		requestLatency:  RequestLatency.With("service", "Balance"),
	}
}

func (m metricsBalance) GetBalance(ctx context.Context, id types.ID) (user types.Balance, err error) {

	defer func(begin time.Time) {
		m.requestLatency.With("method", "getBalance", "success", fmt.Sprint(err == nil)).Observe(time.Since(begin).Seconds())
	}(time.Now())

	defer m.requestCount.With("method", "getBalance", "success", fmt.Sprint(err == nil)).Add(1)

	m.requestCountAll.With("method", "getBalance").Add(1)

	return m.next.GetBalance(ctx, id)
}
