// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/dapr-example/interfaces"
	"github.com/sah4ez/dapr-example/interfaces/types"
)

type BalanceGetBalance func(ctx context.Context, id types.ID) (user types.Balance, err error)

type MiddlewareBalance func(next interfaces.Balance) interfaces.Balance

type MiddlewareBalanceGetBalance func(next BalanceGetBalance) BalanceGetBalance
