// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/sah4ez/dapr-example/interfaces/types"

type requestBalanceGetBalance struct {
	Id types.ID `json:"id,omitempty"`
}

type responseBalanceGetBalance struct {
	User types.Balance `json:"user,omitempty"`
}
