// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/dapr-example/interfaces"
	"github.com/sah4ez/dapr-example/interfaces/types"
)

type UserGetNameByID func(ctx context.Context, id types.ID) (user types.User, err error)

type MiddlewareUser func(next interfaces.User) interfaces.User

type MiddlewareUserGetNameByID func(next UserGetNameByID) UserGetNameByID
